INSERT INTO GENRE (genre) VALUES ("Action");
INSERT INTO GENRE (genre) VALUES ("Puzzle");
INSERT INTO DEVELOPER (name) VALUES ("Example Developer");
INSERT INTO DEVELOPER (name) VALUES ("Example Developer 2");
INSERT INTO GAME (title, developer, genre, ageLimit) VALUES ("Example Game", 1, 1, 18);
INSERT INTO GAME (title, developer, genre) VALUES ("Example Puzzle Game", 2, 2);
INSERT INTO GAME (title, developer, genre) VALUES ("Example Action Game", 1, 2);
INSERT INTO USER (userName, fName, lName) VALUES ("bdawg, Andrew, Besmer");
INSERT INTO USER (userName, fName, lName, birthdate) VALUES ("Dovah", "Max", "Ferney", 1997-05-23);
INSERT INTO USER (userName, fName) VALUES ("Mezna", "Michael");